#include "cli_lib.hpp"

#include "openscad_cpp_evaluator/debug_repl.hpp"
#include "openscad_cpp_evaluator/eval_error.hpp"
#include "openscad_cpp_evaluator/eval_use.hpp"
#include "openscad_cpp_evaluator/evaluator.hpp"
#include "openscad_cpp_evaluator/export.hpp"

#include "openscad_cpp_parser/api.hpp"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <optional>
#include <sstream>

// Mirrors just enough of openscad_evaluator's own cli.py to prove the
// pipeline end to end: format-from-extension dispatch, and --debug
// dropping into a gdb-style REPL (debug_repl.hpp) instead of running
// straight through.
namespace oscadeval {

namespace {

std::string formatForPath(const std::string& explicitFormat, const std::string& outputPath) {
    if (!explicitFormat.empty()) return explicitFormat;
    std::string ext = std::filesystem::path(outputPath).extension().string();
    std::transform(ext.begin(), ext.end(), ext.begin(), [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
    if (ext == ".stl") return "stl";
    if (ext == ".obj") return "obj";
    if (ext == ".off") return "off";
    if (ext == ".3mf") return "3mf";
    return "";
}

// Plain-text --profile report: a summary of resolve/generate/total time,
// then one row per call site sorted by self time descending (ties broken
// by call location/name, so the ordering is deterministic run to run --
// ProfileResult's own std::map storage order isn't self-time order).
// Ported identically (same column layout, same tie-break rule) to the
// Python reference's own _format_profile_report in cli.py, so a report
// generated by either CLI on the same script looks the same.
std::string formatProfileReport(const std::string& sourcePath, const ProfileResult& profile) {
    std::vector<CallSiteProfile> sites = profile.callSites;
    std::sort(sites.begin(), sites.end(), [](const CallSiteProfile& a, const CallSiteProfile& b) {
        if (a.selfTime != b.selfTime) return a.selfTime > b.selfTime;
        if (a.callOrigin != b.callOrigin) return a.callOrigin < b.callOrigin;
        if (a.callLine != b.callLine) return a.callLine < b.callLine;
        return a.name < b.name;
    });

    std::ostringstream out;
    out << "Profile report for " << sourcePath << "\n\n";
    out << std::fixed << std::setprecision(6);
    out << "Total time:      " << profile.totalTime << "s\n";
    out << "  resolve:       " << profile.resolveTime << "s\n";
    out << "  generate:      " << profile.generateTime << "s\n";
    out << "  unattributed:  " << profile.unattributedTime << "s\n\n";

    out << std::left << std::setw(8) << "kind" << " " << std::setw(24) << "name" << " " << std::setw(24) << "caller"
        << " " << std::setw(28) << "location" << " " << std::right << std::setw(6) << "calls" << " " << std::setw(12)
        << "self(s)" << " " << std::setw(14) << "cumulative(s)" << "\n";

    for (const CallSiteProfile& site : sites) {
        const std::string& origin = site.callOrigin.empty() ? sourcePath : site.callOrigin;
        const std::string location = std::filesystem::path(origin).filename().string() + ":" + std::to_string(site.callLine);
        out << std::left << std::setw(8) << site.kind << " " << std::setw(24) << site.name << " " << std::setw(24)
            << site.callerName << " " << std::setw(28) << location << " " << std::right << std::setw(6) << site.callCount
            << " " << std::setw(12) << std::fixed << std::setprecision(6) << site.selfTime << " " << std::setw(14)
            << std::fixed << std::setprecision(6) << site.cumulativeTime << "\n";
    }
    return out.str();
}

} // namespace

int runCli(const std::vector<std::string>& args, std::istream& in, std::ostream& out, std::ostream& err) {
    std::string inputPath;
    std::string outputPath;
    std::string format;
    std::string profilePath;
    bool debug = false;
    for (size_t i = 0; i < args.size(); ++i) {
        const std::string& arg = args[i];
        if (arg == "-o" && i + 1 < args.size()) {
            outputPath = args[++i];
        } else if (arg == "--format" && i + 1 < args.size()) {
            format = args[++i];
        } else if (arg == "--profile" && i + 1 < args.size()) {
            profilePath = args[++i];
        } else if (arg == "--debug") {
            debug = true;
        } else if (inputPath.empty()) {
            inputPath = arg;
        }
    }
    if (inputPath.empty() || outputPath.empty()) {
        err << "usage: openscad-cpp-evaluator <input.scad> -o <output.{stl,obj,off,3mf}> [--format stl|obj|off|3mf] "
               "[--profile FILENAME] [--debug]\n";
        return 1;
    }
    const std::string fmt = formatForPath(format, outputPath);
    if (fmt.empty()) {
        err << "error: cannot infer output format from '" << outputPath << "' -- pass --format\n";
        return 1;
    }

    try {
        std::vector<std::unique_ptr<oscad::ASTNode>> ast = oscad::getASTFromFile(inputPath);
        ResolvedUseScopes used = resolveUseScopes(ast, inputPath, [&out](const std::string& msg) { out << msg << "\n"; });

        std::optional<DebugRepl> repl;
        DebugHooks hooks;
        if (debug) {
            repl.emplace(inputPath, in, out);
            repl->installInterruptHandler(); // Ctrl+C during evaluate() pauses like a breakpoint
            // linenoise reads/writes the real stdin/stdout file descriptors
            // directly, not `in`/`out` themselves -- only turn it on when
            // those really are std::cin/std::cout (genuine interactive use),
            // never for the test suite's injected istringstream/ostringstream.
            if (&in == &std::cin && &out == &std::cout) repl->enableLineEditing();
            if (!repl->runPrompt()) return 0; // user quit before "run"
            hooks.debugHook = [&](int line, int depth, bool forced, const std::string& origin,
                                   const std::vector<CallStackFrame>& callStack, const DebugFramesFn& getFrame) {
                return repl->debugHook(line, depth, forced, origin, callStack, getFrame);
            };
            hooks.errorBreak = [&](int line, const std::string& header, const std::string& origin,
                                    const std::vector<CallStackFrame>& callStack, const DebugFramesFn& getFrame) {
                repl->errorBreak(line, header, origin, callStack, getFrame);
            };
            hooks.returnHook = [&](const std::string& name, const Value& result, int depth) {
                repl->returnHook(name, result, depth);
            };
        }

        Evaluator evaluator([&out](const std::string& msg) { out << msg << "\n"; }, nullptr, nullptr, hooks,
                             /*profiling=*/!profilePath.empty());
        if (repl) repl->attachEvaluator(evaluator); // lets "child" read Evaluator::lastChildrenPositions()
        EvalContext ctx = EvalContext::makeRoot(used.rootScope.get());

        std::vector<ColoredBody> bodies = toRenderableBodies(evaluator.evaluate(used.processedNodes, ctx));

        if (!profilePath.empty()) {
            std::ofstream profileFile(profilePath);
            if (!profileFile) {
                err << "error: cannot open '" << profilePath << "' for writing\n";
                return 1;
            }
            profileFile << formatProfileReport(inputPath, *evaluator.profileResult);
        }

        if (fmt == "stl") {
            writeStl(outputPath, bodies);
        } else if (fmt == "obj") {
            writeObj(outputPath, bodies);
        } else if (fmt == "off") {
            writeOff(outputPath, bodies);
        } else {
            writeThreeMf(outputPath, bodies);
        }
        out << "Exported to " << outputPath << "\n";
        return 0;
    } catch (const oscad::ParseError& e) {
        err << e.what() << "\n";
        return 1;
    } catch (const EvalError& e) {
        // e.what() is already the fully formatted "ERROR: ...\nTRACE: ..."
        // message (see eval_error.hpp) -- no extra prefix here, unlike the
        // generic catch below.
        err << e.what() << "\n";
        return 1;
    } catch (const std::exception& e) {
        err << "ERROR: " << e.what() << "\n";
        return 1;
    }
}

} // namespace oscadeval
