// Printing a function literal back out as source, the way the reference
// spells it when you `str()` or `echo()` one.
//
// Neither existing printer would do. The parser's own ASTNode::toString()
// is precedence-MINIMAL -- it drops any parenthesis the grammar does not
// need -- and 94 places inside the parser depend on that spelling. The
// reference is the opposite: it parenthesises every binary operator and
// every ternary whether or not precedence requires it, so `f(a + b)` comes
// back as `f((a + b))`.
//
// BOSL2's fnliterals tests compare these strings exactly (61 of them), so
// this has to agree with the reference character for character. Every rule
// below was read off the reference by echoing the shape and copying what it
// printed -- see test_format_closure.cpp, which carries the same shapes as
// cases.
#include "openscad_cpp_evaluator/format_closure.hpp"

#include <string>

#include "openscad_cpp_parser/ast.hpp"

namespace oscadeval {
namespace {

using oscad::ASTNode;
using oscad::NodeKind;

std::string fmt(const ASTNode& n);

// `(a + b)`, always. The reference parenthesises a binary operator
// unconditionally -- nesting one inside another gives `((a + b) + c)`, and
// even a call argument gets them: `f((a + b))`.
//
// Templated on the node type rather than casting every operator to one of
// them. The binary classes are generated by a single macro so they do share
// a layout, but they are distinct types with no common binary base, and
// casting a MultiplicationOp to an AdditionOp would be undefined however
// reliably it happens to work.
template <typename T>
std::string binary(const ASTNode& n, const char* op) {
    const auto& e = static_cast<const T&>(n);
    return "(" + fmt(*e.left) + " " + op + " " + fmt(*e.right) + ")";
}

// `-x`, not `(-x)`. A unary operator is never parenthesised itself, though
// its operand still follows the rules: `-(a + b)`.
template <typename T>
std::string unary(const ASTNode& n, const char* op) {
    const auto& e = static_cast<const T&>(n);
    return std::string(op) + fmt(*e.expr);
}

template <typename Seq>
std::string join(const Seq& items, const char* sep) {
    std::string out;
    for (size_t i = 0; i < items.size(); ++i) {
        if (i) out += sep;
        out += fmt(*items[i]);
    }
    return out;
}

// A list-comprehension body is wrapped, on top of whatever the body itself
// prints: `[for(i = [0 : a]) ((i + 1))]`, and `(i)` for a bare identifier.
// A plain vector element is NOT wrapped -- `[1, (2 + 3), a]` -- so the
// parentheses belong to for/if/each rather than to the vector.
std::string wrapped(const ASTNode& n) { return "(" + fmt(n) + ")"; }

std::string fmt(const ASTNode& n) {
    switch (n.kind()) {
    case NodeKind::Identifier:
        return static_cast<const oscad::Identifier&>(n).name;
    case NodeKind::StringLiteral:
    case NodeKind::NumberLiteral:
    case NodeKind::BooleanLiteral:
    case NodeKind::UndefinedLiteral:
        // The parser already spells these the way the reference does,
        // escaping and number formatting included.
        return n.toString();

    case NodeKind::RangeLiteral: {
        const auto& r = static_cast<const oscad::RangeLiteral&>(n);
        // implicitStep, not just `step != nullptr`: the parser fills in a
        // step of 1 for `[0:a]`, and printing it back gives `[0 : 1 : a]`
        // where the reference says `[0 : a]`. The flag is there to tell the
        // two apart.
        std::string s = "[" + fmt(*r.start) + " : ";
        if (r.step && !r.implicitStep) s += fmt(*r.step) + " : ";
        return s + fmt(*r.end) + "]";
    }

    case NodeKind::UnaryMinusOp: return unary<oscad::UnaryMinusOp>(n, "-");
    case NodeKind::LogicalNotOp: return unary<oscad::LogicalNotOp>(n, "!");
    case NodeKind::BitwiseNotOp: return unary<oscad::BitwiseNotOp>(n, "~");

    case NodeKind::AdditionOp:            return binary<oscad::AdditionOp>(n, "+");
    case NodeKind::SubtractionOp:         return binary<oscad::SubtractionOp>(n, "-");
    case NodeKind::MultiplicationOp:      return binary<oscad::MultiplicationOp>(n, "*");
    case NodeKind::DivisionOp:            return binary<oscad::DivisionOp>(n, "/");
    case NodeKind::ModuloOp:              return binary<oscad::ModuloOp>(n, "%");
    case NodeKind::ExponentOp:            return binary<oscad::ExponentOp>(n, "^");
    case NodeKind::BitwiseAndOp:          return binary<oscad::BitwiseAndOp>(n, "&");
    case NodeKind::BitwiseOrOp:           return binary<oscad::BitwiseOrOp>(n, "|");
    case NodeKind::BitwiseShiftLeftOp:    return binary<oscad::BitwiseShiftLeftOp>(n, "<<");
    case NodeKind::BitwiseShiftRightOp:   return binary<oscad::BitwiseShiftRightOp>(n, ">>");
    case NodeKind::LogicalAndOp:          return binary<oscad::LogicalAndOp>(n, "&&");
    case NodeKind::LogicalOrOp:           return binary<oscad::LogicalOrOp>(n, "||");
    case NodeKind::EqualityOp:            return binary<oscad::EqualityOp>(n, "==");
    case NodeKind::InequalityOp:          return binary<oscad::InequalityOp>(n, "!=");
    case NodeKind::GreaterThanOp:         return binary<oscad::GreaterThanOp>(n, ">");
    case NodeKind::GreaterThanOrEqualOp:  return binary<oscad::GreaterThanOrEqualOp>(n, ">=");
    case NodeKind::LessThanOp:            return binary<oscad::LessThanOp>(n, "<");
    case NodeKind::LessThanOrEqualOp:     return binary<oscad::LessThanOrEqualOp>(n, "<=");

    case NodeKind::TernaryOp: {
        const auto& t = static_cast<const oscad::TernaryOp&>(n);
        return "(" + fmt(*t.condition) + " ? " + fmt(*t.trueExpr) + " : " + fmt(*t.falseExpr) + ")";
    }

    case NodeKind::PrimaryCall: {
        const auto& c = static_cast<const oscad::PrimaryCall&>(n);
        return fmt(*c.left) + "(" + join(c.arguments, ", ") + ")";
    }
    case NodeKind::PrimaryIndex: {
        const auto& i = static_cast<const oscad::PrimaryIndex&>(n);
        return fmt(*i.left) + "[" + fmt(*i.index) + "]";
    }
    case NodeKind::PrimaryMember: {
        const auto& m = static_cast<const oscad::PrimaryMember&>(n);
        return fmt(*m.left) + "." + m.member->name;
    }

    case NodeKind::PositionalArgument:
        return fmt(*static_cast<const oscad::PositionalArgument&>(n).expr);
    case NodeKind::NamedArgument: {
        const auto& a = static_cast<const oscad::NamedArgument&>(n);
        return a.name->name + " = " + fmt(*a.expr);
    }
    case NodeKind::Assignment: {
        const auto& a = static_cast<const oscad::Assignment&>(n);
        return a.name->name + " = " + fmt(*a.expr);
    }
    case NodeKind::ParameterDeclaration: {
        const auto& p = static_cast<const oscad::ParameterDeclaration&>(n);
        return p.defaultValue ? p.name->name + " = " + fmt(*p.defaultValue) : p.name->name;
    }

    case NodeKind::FunctionLiteral: {
        const auto& f = static_cast<const oscad::FunctionLiteral&>(n);
        return "function(" + join(f.parameters, ", ") + ") " + fmt(*f.body);
    }
    case NodeKind::LetOp: {
        const auto& l = static_cast<const oscad::LetOp&>(n);
        // Body bare: `let(c = (a + b)) c`. What looks like a wrapped body
        // in `let(a = 1) (a + x)` is the binary parenthesising itself.
        return "let(" + join(l.assignments, ", ") + ") " + fmt(*l.body);
    }
    case NodeKind::EchoOp: {
        const auto& e = static_cast<const oscad::EchoOp&>(n);
        return "echo(" + join(e.arguments, ", ") + ") " + fmt(*e.body);
    }
    case NodeKind::AssertOp: {
        const auto& a = static_cast<const oscad::AssertOp&>(n);
        return "assert(" + join(a.arguments, ", ") + ") " + fmt(*a.body);
    }

    case NodeKind::ListComprehension: {
        const auto& c = static_cast<const oscad::ListComprehension&>(n);
        return "[" + join(c.elements, ", ") + "]";
    }
    case NodeKind::ListCompFor: {
        const auto& f = static_cast<const oscad::ListCompFor&>(n);
        return "for(" + join(f.assignments, ", ") + ") " + wrapped(*f.body);
    }
    case NodeKind::ListCompCFor: {
        const auto& f = static_cast<const oscad::ListCompCFor&>(n);
        // The odd one out: no space after the semicolons, and the body is
        // NOT wrapped -- `[for(i = 0;(i < a);i = (i + 1)) i]`.
        return "for(" + join(f.inits, ", ") + ";" + fmt(*f.condition) + ";" +
               join(f.incrs, ", ") + ") " + fmt(*f.body);
    }
    case NodeKind::ListCompIf: {
        const auto& i = static_cast<const oscad::ListCompIf&>(n);
        return "if(" + fmt(*i.condition) + ") " + wrapped(*i.trueExpr);
    }
    case NodeKind::ListCompIfElse: {
        const auto& i = static_cast<const oscad::ListCompIfElse&>(n);
        return "if(" + fmt(*i.condition) + ") " + wrapped(*i.trueExpr) +
               " else " + wrapped(*i.falseExpr);
    }
    case NodeKind::ListCompEach: {
        const auto& e = static_cast<const oscad::ListCompEach&>(n);
        return "each " + wrapped(*e.body);
    }
    case NodeKind::ListCompLet: {
        const auto& l = static_cast<const oscad::ListCompLet&>(n);
        return "let(" + join(l.assignments, ", ") + ") " + fmt(*l.body);
    }

    case NodeKind::CommentedExpr:
        // Comments are not part of what the reference prints.
        return fmt(*static_cast<const oscad::CommentedExpr&>(n).expr);

    default:
        // Anything not reachable from inside a function literal's body --
        // statements, module instantiations, include directives. Falling
        // back to the parser's own spelling is closer than an empty string,
        // and the value here is diagnostic rather than compared.
        return n.toString();
    }
}

} // namespace

std::string formatFunctionLiteral(const oscad::FunctionLiteral& fn) { return fmt(fn); }

} // namespace oscadeval
