# Reads IN_FILE (binary) and writes OUT_FILE: a C++ header exposing its
# bytes as a static array (kBundledFontData/kBundledFontDataSize). Run via
# `cmake -DIN_FILE=... -DOUT_FILE=... -P embed_font.cmake` as a build-time
# add_custom_command, not configure_file -- a font baked in as bytes has no
# runtime file path to go stale once the shared library is installed
# somewhere other than its own build tree (see this script's own call site
# in the top-level CMakeLists.txt for the packaging bug this replaces).
if(NOT DEFINED IN_FILE OR NOT DEFINED OUT_FILE)
    message(FATAL_ERROR "embed_font.cmake requires -DIN_FILE=... -DOUT_FILE=...")
endif()

file(READ "${IN_FILE}" _hex HEX)
string(LENGTH "${_hex}" _hexLen)
math(EXPR _byteCount "${_hexLen} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytesCsv "${_hex}")

file(WRITE "${OUT_FILE}"
"// Auto-generated by cmake/embed_font.cmake from ${IN_FILE} -- do not edit.
#pragma once
#include <cstddef>

namespace oscadeval {
inline constexpr unsigned char kBundledFontData[] = {
${_bytesCsv}
};
inline constexpr std::size_t kBundledFontDataSize = ${_byteCount};
} // namespace oscadeval
")
