# Reads IN_FILES (a ";"-separated list of binaries) and writes OUT_FILE: a
# C++ header exposing their bytes as static arrays, plus a kBundledFonts
# table over them. Run via
# `cmake -DIN_FILES="a.ttf;b.ttf" -DOUT_FILE=... -P embed_font.cmake` as a
# build-time add_custom_command, not configure_file -- fonts baked in as
# bytes have no runtime file path to go stale once the shared library is
# installed somewhere other than its own build tree (see this script's own
# call site in the top-level CMakeLists.txt for the packaging bug this
# replaces).
#
# More than one font, because a style= that cannot be satisfied is worse
# than useless: it silently returns the regular face, which is what made
# `fontmetrics(10, "Liberation Sans:style=bold")` report Regular's numbers
# (BelfrySCAD #381). The whole family is embedded so the styles a script
# asks for exist even on a machine with no fonts of its own.
if(NOT DEFINED IN_FILES OR NOT DEFINED OUT_FILE)
    message(FATAL_ERROR "embed_font.cmake requires -DIN_FILES=... -DOUT_FILE=...")
endif()

# "@"-joined by the caller into a single argument; see the call site for
# why neither a ";" list nor a "|" join survives the trip.
string(REPLACE "@" ";" IN_FILES "${IN_FILES}")

set(_decls "")
set(_table "")
set(_index 0)
foreach(_file IN LISTS IN_FILES)
    file(READ "${_file}" _hex HEX)
    string(LENGTH "${_hex}" _hexLen)
    math(EXPR _byteCount "${_hexLen} / 2")
    string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytesCsv "${_hex}")
    get_filename_component(_name "${_file}" NAME)
    string(APPEND _decls
"// ${_name}
inline constexpr unsigned char kBundledFont${_index}[] = {
${_bytesCsv}
};
")
    string(APPEND _table "    {kBundledFont${_index}, ${_byteCount}},\n")
    if(_index EQUAL 0)
        set(_firstSize "${_byteCount}")
    endif()
    math(EXPR _index "${_index} + 1")
endforeach()

file(WRITE "${OUT_FILE}"
"// Auto-generated by cmake/embed_font.cmake -- do not edit.
#pragma once
#include <cstddef>

namespace oscadeval {

${_decls}
struct BundledFont {
    const unsigned char* data;
    std::size_t size;
};

// Index 0 is the default face and the last-resort fallback; the rest are
// the other styles of the same family, so a `style=` request can be met
// without anything installed on the machine.
inline constexpr BundledFont kBundledFonts[] = {
${_table}};
inline constexpr std::size_t kBundledFontCount = ${_index};

// The default face, named for the callers that only ever wanted that one.
inline constexpr const unsigned char* kBundledFontData = kBundledFont0;
inline constexpr std::size_t kBundledFontDataSize = ${_firstSize};

} // namespace oscadeval
")
